### ISSUE TITLE
No internet found using qemu-system-x86_64

### ISSUE THREAD

**Issue by nullchilly** [ChefKissInc/qemu-apple-silicon#18]
I need an internet connection to complete this step https://github.com/TrungNguyen1909/qemu-t8030/wiki/USB-and-Restore#restore-ios-firmware

# Works fine using the archived [qemu-t8030](https://github.com/TrungNguyen1909/qemu-t8030/)

```sh
./qemu-t8030/build/qemu-system-x86_64 -boot order=c -m 1024 -vga none -device virtio-vga,xres=640,yres=480 -cpu qemu64 -usb -device usb-ehci,id=ehci -device usb-tcp-remote,bus=ehci.0 -drive file=arch.qcow2 -monitor telnet:127.0.0.1:1236,server,nowait
```

# Temporary failure in name resolution using this fork

```sh
./qemu-apple-silicon/build/qemu-system-x86_64 -boot order=c -m 1024 -vga none -device virtio-vga,xres=640,yres=480 -cpu qemu64 -usb -device usb-ehci,id=ehci -device usb-tcp-remote,bus=ehci.0 -drive file=arch.qcow2 -monitor telnet:127.0.0.1:1236,server,nowait
```

I could just use the archived repo to launch linux but I'm curious why it doesn't work here.

**Comment by VisualEhrmanntraut** [comment]
We have been accessing the network just fine both on a Linux host and a macOS host the entire development cycle. This is user error.

**Comment by VisualEhrmanntraut** [comment]
I use macOS and

My build configuration is
```sh
LIBTOOL="glibtool" ../configure --target-list=aarch64-softmmu,x86_64-softmmu --disable-bsd-user --disable-guest-agent --enable-slirp --enable-capstone --enable-curses --enable-libssh --enable-virtfs --enable-zstd --extra-cflags=-DNCURSES_WIDECHAR=1 --disable-sdl --disable-gtk --enable-cocoa --enable-lzfse --disable-werror
```

and I run the companion via
```sh
DYLD_INSERT_LIBRARIES="/usr/local/lib/liblzfse.dylib" ~/Developer/ProjectSources/AppleHax/qemu-apple-silicon/build/qemu-system-x86_64 -M q35 -hda Arch.qcow2 -boot order=d -m 1024 -device usb-ehci,id=ehci -device usb-tcp-remote,bus=ehci.0
```

**Comment by nullchilly** [comment]
Not sure which how to get useful logs for debugging but here's my result on this repo

![image](https://github.com/ChefKissInc/qemu-apple-silicon/assets/56817415/51b773ec-82df-44d5-962b-9729c315a84e)

**Comment by VisualEhrmanntraut** [comment]
Did you enable `systemd-resolved`...?

**Comment by nullchilly** [comment]
It is also unable to reach network on linux, I thought there was some problem with arch so I switched to macos kvm and the same thing happened. Finally I tried the archived qemu-t8030 and it worked

![image](https://github.com/ChefKissInc/qemu-apple-silicon/assets/56817415/a28c793b-33ec-49fd-bbe0-d62fc071b342)

**Comment by nullchilly** [comment]
Weird that I only got the `wrong data byte` warning inside qemu

> it is likely the network configuration you have does not match in my fork because it uses a newer QEMU version

Yeah sounds like it, tysm for your time!

I will use the archived qemu for the linux VM for the time being. Closing..

**Comment by VisualEhrmanntraut** [comment]
https://wiki.archlinux.org/title/Network_configuration should help you in finding out what the problem is for the name resolution error.
<img width="931" alt="Screenshot 2024-04-19 at 12 45 57" src="https://github.com/ChefKissInc/qemu-apple-silicon/assets/30368284/c0027309-2dea-4744-b126-a6dc2af5e2c5">
This one is a QEMU quirk afaik with ICMP and does not affect actual network access.
