### ISSUE TITLE
Upstream to QEMU?

### ISSUE THREAD

**Issue by theoparis** [ChefKissInc/qemu-apple-silicon#8]
Is it possible to upstream these changes to qemu so it isn't required to build a qemu fork that could be very outdated (compared to upstream qemu) at some point?

Update: I have been trying to convert these changes to patch files that work with the latest qemu master branch. It seems like there are a lot of issues with the changes when I ran checkpatch because [you weren't following the QEMU style standards](https://www.qemu.org/docs/master/devel/submitting-a-patch.html).

**Comment by VisualEhrmanntraut** [comment]
I do not consent to this work being given to QEMU or anyone for the matter, thanks. Unlike a certain someone, we continue working on it and don't just create demos for popularity and a job position then leave the community to cope. See the other branch.
Furthermore, why would it be upstreamed to QEMU? It is not even working to the point of showing the GUI
Finally, this work would likely put QEMU in legal trouble with Apple.

**Comment by chris-pcguy** [comment]
https://www.youtube.com/watch?v=sFacWGBJ_cs
If you want to do something, fix bugs and add features.

Probably we will sync to the newest release (not master) after we get more than SEPROM working.

/

**Comment by upintheairsheep** [comment]
> I do not consent to this work being given to QEMU or anyone for the matter, thanks. Unlike a certain someone, we continue working on it and don't just create demos for popularity and a job position then leave the community to cope. See the other branch. Furthermore, why would it be upstreamed to QEMU? It is not even working to the point of showing the GUI Finally, this work would likely put QEMU in legal trouble with Apple.

Are you mentioning Jeremy, Corellium, or the original creator of QEMU-t9080?
